FROM jenkins-upstream-jdk8

USER root

# Install Linux kernal setcap support, lets java open low numbered ports as non-root
RUN apt-get update                  \
 && apt-get install -y libcap2-bin  \
 && rm -rf /var/lib/apt/lists/*
RUN setcap 'cap_net_bind_service=+ep' "${JAVA_HOME}/bin/java"

# Debugging utilities
RUN apt-get update          \
 && apt-get install -y vim  \
 && rm -rf /var/lib/apt/lists/*

USER jenkins

# Install plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Remove black-listed plugins
RUN for plugin in       \
        ldap            \
        windows-slaves  \
        ; do \
    touch /usr/share/jenkins/ref/plugins/${plugin}.jpi.disabled; \
done

# Download HTTP/2 jdk-8 ALPN support
# https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions
# 1.8.0_212 => https://repo.maven.apache.org/maven2/org/mortbay/jetty/alpn/alpn-boot/8.1.13.v20181017/alpn-boot-8.1.13.v20181017.jar
ARG MVN_URL=https://repo.maven.apache.org/maven2
ARG jettyVersion=9.4.26.v20200117
ARG alpnVersion=8.1.13.v20181017
RUN curl --create-dirs -sSLo \
      /usr/share/jenkins/ref/extraLibs/jetty-alpn-server-${jettyVersion}.jar \
      ${MVN_URL}/org/eclipse/jetty/jetty-alpn-server/${jettyVersion}/jetty-alpn-server-${jettyVersion}.jar \
 && curl --create-dirs -sSLo \
      /usr/share/jenkins/ref/extraLibs/jetty-alpn-openjdk8-server-${jettyVersion}.jar \
      ${MVN_URL}/org/eclipse/jetty/jetty-alpn-openjdk8-server/${jettyVersion}/jetty-alpn-openjdk8-server-${jettyVersion}.jar \
 && curl --create-dirs -sSLo \
      /usr/share/jenkins/ref/bootclasspath/alpn-boot-${alpnVersion}.jar \
      ${MVN_URL}/org/mortbay/jetty/alpn/alpn-boot/${alpnVersion}/alpn-boot-${alpnVersion}.jar
RUN chmod o+rx /usr/share/jenkins/ref/extraLibs \
               /usr/share/jenkins/ref/bootclasspath

# Custom plugin builds
RUN mkdir -p /usr/share/jenkins/ref/plugins
COPY plugins/github-oauth-plugin/target/github-oauth.hpi  /usr/share/jenkins/ref/plugins

# Config Files
COPY files/logging.properties /usr/share/jenkins/ref/logging.properties
COPY files/.gitconfig         /usr/share/jenkins/ref/.gitconfig

# Config Scripts
COPY init-scripts/*.groovy /usr/share/jenkins/ref/init.groovy.d/

# Set admin user, Disable Upgrade Wizard, Disable Kill Switch
RUN mkdir -p /var/jenkins_home/secrets;                                            \
    echo 'admin' > /var/jenkins_home/secrets/initialAdminPassword;                 \
    echo '2.0'   > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state;     \
    echo 'false' > /var/jenkins_home/secrets/slave-to-master-security-kill-switch

# Modified launcher
COPY jenkins-jdk8.sh /usr/local/bin/jenkins.sh

# Configuration as Code yaml file(s)
COPY files/jenkins.yaml /usr/share/jenkins/ref/

ARG FOOTER_URL
ENV FOOTER_URL=${FOOTER_URL}
