---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-system
  name: aws-iam-authenticator
  labels:
    k8s-app: aws-iam-authenticator
data:
  config.yaml: |
    clusterID: 1-16-a-dev.kops.cicdenv.com
    server:
      mapUsers:
      - userARN: arn:aws:iam::014719181291:user/users/fvogt
        username: fvogt
        groups:
        - system:masters
      mapRoles:
      - roleARN: arn:aws:iam::977594567050:role/dev-admin
        username: kubernetes-admin
        groups:
        - system:masters
