---
- name: install required ephemeral-disks packages
  apt:
    name: ['mdadm', 'nvme-cli']
    state: present
    update_cache: yes

- name: copy init-ephemeral-disks.sh
  copy: src=init-ephemeral-disks.sh dest=/usr/local/bin/init-ephemeral-disks.sh mode=0755 owner=root group=root
  register: init_ephemeral_disks_script

- name: check init-ephemeral-disks service unit file
  stat: path=/etc/systemd/system/init-ephemeral-disks.service
  register: init_ephemeral_disks_unit_file

- name: init-ephemeral-disks service unit file
  template: src=init-ephemeral-disks.service.j2 dest=/etc/systemd/system/init-ephemeral-disks.service mode=0644 owner=root group=root
  register: init_ephemeral_disks_systemd_unit

- name: systemd daemon-reload
  systemd:
    name: init-ephemeral-disks
    daemon_reload: yes

- name: start init-ephemeral-disks service
  systemd: name=init-ephemeral-disks state=stopped enabled=yes
