- name: install apt packages
  apt:
    pkg:
      - atop
      - bridge-utils
      - build-essential
      - dstat
      - fio
      - glances
      - iftop
      - ioping
      - iotop
      - inxi
      - ipcalc
      - iptraf
      - jq
      - mtr
      - multitail
      - netcat
      - nethogs
      - nicstat
      - sysstat
      - unzip

- name: install aws cli bundle prereqs
  apt:
    pkg:
      - python3-pip
      - python3-venv
      - python-is-python3

- name: remove amazon-ssm-agent
  snap:
    name: amazon-ssm-agent
    state: absent

- name: install latest aws cli bundle
  shell: |
    set -e

    curl -sL "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    unzip awscli-bundle.zip
    ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    rm awscli-bundle.zip
  args:
    creates: /usr/local/bin/aws
