---
- name: Control Docker Group ID
  group:
    name: docker
    gid: 8088
    state: present

- name: Add Docker CE GPG key
  apt_key: url=https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Install required packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add Docker CE APT repository
  apt_repository:
    #     deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_channel }}

- name: Install Docker CE
  apt:
    name: ['docker-ce']
    state: present

- name: Install Docker AWS ECR credentials helper
  apt:
    name: ['amazon-ecr-credential-helper']
    state: present

- name: Root user docker conf directory
  file:
    path: /root/.docker
    state: directory
    mode: 0755

- name: Root user docker conf file
  copy:
    src: files/config.json
    dest: /root/.docker/config.json

- name: Sysconfig folder
  file:
    path: /etc/sysconfig
    state: directory
    mode: 0755

- name: Sysconfig containerd env file
  copy:
    src: files/etc/sysconfig/containerd
    dest: /etc/sysconfig/containerd

- name: Custom containerd conf file
  copy:
    src: files/etc/containerd/custom-config.toml
    dest: /etc/containerd/custom-config.toml

- name: Custom containerd service unit
  copy:
    src: files/lib/systemd/system/containerd.service
    dest: /lib/systemd/system/containerd.service
  notify:
    - restart containerd

- name: Sysconfig docker env file
  copy:
    src: files/etc/sysconfig/docker
    dest: /etc/sysconfig/docker

- name: Custom docker service unit
  copy:
    src: files/lib/systemd/system/docker.service
    dest: /lib/systemd/system/docker.service
  notify:
    - restart docker
