---
- name: Control Docker Group ID
  group:
    name: docker
    gid: 8088
    state: present

- name: Add Docker CE GPG key
  apt_key: url=https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Install required packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add Docker CE APT repository
  apt_repository:
    #     deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_channel }}

- name: Install Docker CE
  apt:
    name: ['docker-ce']
    state: present

- name: Install Docker AWS ECR credentials helper
  apt:
    name: ['amazon-ecr-credential-helper']
    state: present

- name: Root user docker conf directory
  file:
    path: /root/.docker
    state: directory
    mode: 0755

- name: Root user docker conf file
  copy:
    src: files/config.json
    dest: /root/.docker/config.json
