- name: node_exporter service unit file
  copy:
    src: etc/systemd/system/node-exporter.service
    dest: /etc/systemd/system/node-exporter.service
    mode: 0644
    owner: root
    group: root

- name: node_exporter service env file
  template: 
    src: etc/systemd/system/node-exporter.env.j2 
    dest: /etc/systemd/system/node-exporter.env
    mode: 0644 
    owner: root 
    group: root
